resources:
- name: every-morning
  type: time
  source:
    start: 9:40 AM
    stop: 9:45 AM
    location: Europe/Dublin
    days:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday

- name: every-evening
  type: time
  source:
    start: 6:00 PM
    stop: 6:30 PM
    location: Europe/Dublin
    days:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday

- name: github-code
  type: git
  source:
    uri: https://github.com/vlad-stoian/robbit.git
    branch: master

jobs:
- name: post-retro-items
  plan:
  - get: every-morning
    trigger: true
  - get: github-code
  - task: annoy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: alpine
      inputs:
      - name: github-code
      run:
        path: python
        args:
        - "github-code/src/post-retro-items.py"
        - {{postfacto-token}}
        - {{retro-id}}
        - {{slack-token}}
        - {{slack-channel}}

- name: update-channel-topic
  plan:
  - get: every-morning
    trigger: true
  - get: github-code
  - task: annoy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: alpine
      inputs:
      - name: github-code
      run:
        path: python
        args:
        - "github-code/src/update-channel-topic.py"
        - {{slack-token}}
        - {{slack-channel}}

- name: clear-channel-topic
  plan:
  - get: every-evening
    trigger: true
  - get: github-code
  - task: annoy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: alpine
      inputs:
      - name: github-code
      run:
        path: python
        args:
        - "github-code/src/clear-channel-topic.py"
        - {{slack-token}}
        - {{slack-channel}}
